### ISSUE TITLE
New style for the menu

### ISSUE THREAD

**Issue by tzclucian** [EDU-Soft/hci-project#1]
Make the toolbox look better.

Add darker color for the title.
Add lighther color for the options

Make the board instruments stay fixed above the shapes.

The board specific instruments will be a darker yellow and the instruments will be lighter.

All the other shapes will have a darker blue for the title, ligher blue for the sub instruments.

Also highlight current/last used shape.

Toolbox:
color
width
Basic instruments (title, with sub options always visible)
- clean board
- select shape
- deselect shape
- duplicate shape
- delete shape
  Triangle
  -
  -
  Quadri
  -
  -
  ....

**Comment by tzclucian** [comment]
fixed by @MihaiMariusBaciu

**Comment by tzclucian** [comment]
The overall implementation is ok but can you make the borders darker? you can't distinguish the colors very well atm.

**Comment by tzclucian** [comment]
I really like the menu from here: http://harvest.research.chop.edu/demo/query/
Would it be hard to switch to that style?

Let's discuss more about this menu / helper / toolbox on Wednesday with the prof.
(Don't implement it yet)

**Comment by tzclucian** [comment]
![img_20150513_192657](https://cloud.githubusercontent.com/assets/10231850/7615494/ad3b0b08-f9a6-11e4-9285-f59cf72495bd.jpg)
![img_20150513_192708](https://cloud.githubusercontent.com/assets/10231850/7615493/ad3a39e4-f9a6-11e4-8d33-d101494b4f41.jpg)
![img_20150513_192715](https://cloud.githubusercontent.com/assets/10231850/7615492/ad3a394e-f9a6-11e4-9150-e975b7a719bd.jpg)

**Comment by ghost** [comment]
Am adăugat structură, ami rămân finisajele şi sa văd ce am omis

**Comment by tzclucian** [comment]
This was broken on chrome.

I did some changes and the new menu is broken for good now.

**Comment by ghost** [comment]
I have pushed the changes for the top bar, and removed a horizontal scroll that appear.

**Comment by ghost** [comment]
We must investigate the bug on chrome since I have made the changes using chrome.

**Comment by tzclucian** [comment]
![img_20150521_113943](https://cloud.githubusercontent.com/assets/10231850/7744707/3812e252-ffae-11e4-9505-9d67b1c534a0.jpg)

The design for the small squares that contain the instruments.

This design applies to every tile that appers in the menu **including color and width** tiles.

**Comment by tzclucian** [comment]
fixed by @MihaiMariusBaciu
