### ISSUE TITLE
Voice recognition API integration

### ISSUE THREAD

**Issue by tzclucian** [EDU-Soft/hci-project#10]
Implement a similiar method to get the text from the voice to https://www.google.com/intl/en/chrome/demos/speech.html.

You can find the example behind that web page: https://github.com/GoogleChrome/webplatform-samples/blob/master/webspeechdemo/webspeechdemo.html

**Comment by tzclucian** [comment]
Done by @Marian-Pinzariu

**Comment by Marian-Pinzariu** [comment]
Thanks for closing this Lucian.
