### ISSUE TITLE
Color & Width properties

### ISSUE THREAD

**Issue by tzclucian** [EDU-Soft/hci-project#12]
As we discussed last Thursday please move the color and width outside of the "menu", in order to have them always visible.

Also add a label before them, "Colour" and "Width".

**Comment by tzclucian** [comment]
fixed by @MihaiMariusBaciu

**Comment by tzclucian** [comment]
They still need to have the speaker icon that will be the help. Reopening.

**Comment by ghost** [comment]
They should have the speaker icon.

**Comment by ghost** [comment]
If you try to change the value of the height from the inspector the whiteboard remains where it is (the part that has the grid)

**Comment by ghost** [comment]
I looked in the html of the master branch and the volume icon appear.

**Comment by ghost** [comment]
I will look into them a little later

**Comment by tzclucian** [comment]
fixed by @MihaiMariusBaciu
