### ISSUE TITLE
Eliminate useless scroll in page

### ISSUE THREAD

**Issue by tzclucian** [EDU-Soft/hci-project#14]
What the title says.

**Comment by tzclucian** [comment]
There is still plenty of space under the details bar that can be used by the canvas.

![screenshot 2015-05-12 20 39 44](https://cloud.githubusercontent.com/assets/10231850/7594087/18553172-f8e7-11e4-846e-cda701e24903.png)

**Comment by ghost** [comment]
I know but there is a little problem with the whiteboard, it uses a fix height when creating it, so auto will not work

**Comment by tzclucian** [comment]
Done.
