### ISSUE TITLE
Toolbar overlaps command input

### ISSUE THREAD

**Issue by tzclucian** [EDU-Soft/hci-project#18]
Can you please make that it doesn't overlap the input?

![screenshot 2015-05-25 18 36 08](https://cloud.githubusercontent.com/assets/10231850/7799304/046e0df2-030d-11e5-8a5a-09f65c3cec70.png)

**Comment by ghost** [comment]
I can make it smaller

**Comment by ghost** [comment]
It will end above the details bar

**Comment by tzclucian** [comment]
Perfect! Resize whenever you got the time please.

**Comment by ghost** [comment]
Fixed
