### ISSUE TITLE
Implement undo/redo

### ISSUE THREAD

**Issue by tzclucian** [EDU-Soft/hci-project#23]

**Comment by ghost** [comment]
fixed

**Comment by tzclucian** [comment]
Please add speaker icons for command help.

**Comment by ghost** [comment]
than we remove the popover on the command itself ?

**Comment by tzclucian** [comment]
I'm thinking of a new design for the undo/redo as for the moment we support the command history aswell.

**Comment by tzclucian** [comment]
Implemented.
