### ISSUE TITLE
Draw triangle commands

### ISSUE THREAD

**Issue by tzclucian** [EDU-Soft/hci-project#26]

**Comment by Marian-Pinzariu** [comment]
General triangle: https://github.com/EDU-Soft/hci-project/commit/f670836053324809b84740a868f2d46d5f4633d7

**Comment by Marian-Pinzariu** [comment]
Equilateral Triangle: https://github.com/EDU-Soft/hci-project/commit/22a37e5c391e7ce65d91f3108636c31191681d09
