### ISSUE TITLE
Draw quadri commands

### ISSUE THREAD

**Issue by tzclucian** [EDU-Soft/hci-project#27]

**Comment by Marian-Pinzariu** [comment]
Rectangle: https://github.com/EDU-Soft/hci-project/commit/6a819389cab2fd84f05db84c6fde92b9fcfdf558

**Comment by Marian-Pinzariu** [comment]
Square: https://github.com/EDU-Soft/hci-project/commit/221b942f25ce2ec529916a79342d4c23cbf5e064
