### ISSUE TITLE
Cog wheel settings

### ISSUE THREAD

**Issue by tzclucian** [EDU-Soft/hci-project#29]
Under cog wheel settings add list elements with a checkbox infront.

**Comment by tzclucian** [comment]
I saw you added the list items. Don't forget about the checkboxes.

**Comment by ghost** [comment]
I added them locally but we have a problem with the checkbox, when you click on it it will close the popup. I'm thinking of adding a popup that will display the settings and you will close it when you finished checking the settings

**Comment by ghost** [comment]
Added the support for the settings we need to make the actual list of settings.
